server:
  port: 8080  # Port number on which the API Gateway service will run

spring:
  application:
    name: api-gateway  # Logical name of this service, used for service registration and discovery in Eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # URL of the Eureka Server where this service (API Gateway) will register itself
