spring:
  main:
    web-application-type: reactive  # Required for Spring Cloud Gateway (WebFlux)
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL

springdoc:
  swagger-ui:
    urls:
      - name: User Service
        url: http://localhost:8082/v3/api-docs  # Swagger docs for User Service
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, httptrace  # include the endpoints you want
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true
